spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: password
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to the application!
server:
  port: '8082'

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    password: password
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to the application!
server:
  port: '8082'

---

spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    password: password
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to the application!
server:
  port: '8082'
