spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: password
  jpa:
    generate-ddl: 'true'
    hibe:
      ddl-auto: update
    hibernate:
      ddl-auto: create
    show-sql: 'true'
welcome:
  message: Welcome to the application!
server:
  port: '8082'
